In [1]:
import models.learning
import torch

In [12]:
i = torch.rand((1,28, 5,5))

In [13]:
print(i)

tensor([[[[0.0607, 0.1222, 0.9207, 0.9762, 0.8873],
          [0.6058, 0.6135, 0.6200, 0.3524, 0.3695],
          [0.9486, 0.2896, 0.6092, 0.6630, 0.6068],
          [0.8226, 0.8014, 0.0763, 0.7772, 0.4017],
          [0.7366, 0.0884, 0.2235, 0.5658, 0.2945]],

         [[0.5327, 0.0648, 0.3174, 0.3287, 0.1473],
          [0.7106, 0.4618, 0.9363, 0.3382, 0.9589],
          [0.7323, 0.9079, 0.7722, 0.9724, 0.7762],
          [0.2469, 0.6988, 0.5617, 0.3090, 0.5008],
          [0.2986, 0.7210, 0.5754, 0.3769, 0.4015]],

         [[0.0367, 0.5472, 0.6613, 0.6053, 0.6824],
          [0.4217, 0.2895, 0.8327, 0.5414, 0.7331],
          [0.6057, 0.1149, 0.5645, 0.0762, 0.6378],
          [0.3852, 0.5002, 0.9711, 0.5105, 0.3865],
          [0.7388, 0.0090, 0.4767, 0.9085, 0.0413]],

         [[0.4687, 0.3074, 0.7660, 0.4902, 0.7013],
          [0.5246, 0.0445, 0.6474, 0.6985, 0.4680],
          [0.1490, 0.3474, 0.2763, 0.6527, 0.4590],
          [0.7689, 0.3046, 0.3309, 0.5853, 0.6787],
      

In [20]:
s = torch.nn.Softmax(dim=2)(i)

In [21]:
print(s)

tensor([[[[0.1080, 0.1480, 0.2941, 0.2667, 0.2841],
          [0.1862, 0.2419, 0.2177, 0.1429, 0.1693],
          [0.2623, 0.1750, 0.2154, 0.1950, 0.2146],
          [0.2313, 0.2919, 0.1264, 0.2186, 0.1748],
          [0.2122, 0.1431, 0.1464, 0.1769, 0.1571]],

         [[0.2017, 0.1160, 0.1428, 0.1683, 0.1275],
          [0.2409, 0.1725, 0.2651, 0.1699, 0.2872],
          [0.2462, 0.2695, 0.2250, 0.3203, 0.2392],
          [0.1515, 0.2186, 0.1823, 0.1650, 0.1816],
          [0.1596, 0.2235, 0.1848, 0.1766, 0.1644]],

         [[0.1304, 0.2525, 0.1891, 0.2087, 0.2337],
          [0.1916, 0.1952, 0.2244, 0.1958, 0.2459],
          [0.2303, 0.1639, 0.1716, 0.1230, 0.2235],
          [0.1847, 0.2409, 0.2577, 0.1898, 0.1738],
          [0.2631, 0.1474, 0.1572, 0.2827, 0.1231]],

         [[0.2030, 0.1946, 0.2326, 0.1662, 0.2258],
          [0.2147, 0.1496, 0.2066, 0.2046, 0.1788],
          [0.1475, 0.2026, 0.1425, 0.1955, 0.1772],
          [0.2741, 0.1941, 0.1505, 0.1827, 0.2208],
      

In [19]:
print(sum(sum(s[0][0])))

tensor(0.9293)


In [15]:
print(torch.nn.Softmax(dim=1)(i))

tensor([[[[0.0231, 0.0247, 0.0495, 0.0577, 0.0472],
          [0.0357, 0.0389, 0.0369, 0.0329, 0.0295],
          [0.0550, 0.0293, 0.0395, 0.0409, 0.0366],
          [0.0466, 0.0463, 0.0213, 0.0466, 0.0307],
          [0.0415, 0.0242, 0.0251, 0.0396, 0.0299]],

         [[0.0370, 0.0233, 0.0271, 0.0302, 0.0225],
          [0.0396, 0.0334, 0.0506, 0.0324, 0.0533],
          [0.0443, 0.0544, 0.0465, 0.0557, 0.0434],
          [0.0262, 0.0418, 0.0346, 0.0292, 0.0339],
          [0.0268, 0.0456, 0.0357, 0.0328, 0.0333]],

         [[0.0225, 0.0377, 0.0382, 0.0398, 0.0385],
          [0.0297, 0.0281, 0.0456, 0.0397, 0.0425],
          [0.0390, 0.0246, 0.0378, 0.0227, 0.0378],
          [0.0301, 0.0343, 0.0520, 0.0357, 0.0303],
          [0.0416, 0.0224, 0.0324, 0.0558, 0.0232]],

         [[0.0347, 0.0297, 0.0424, 0.0355, 0.0392],
          [0.0329, 0.0220, 0.0379, 0.0464, 0.0326],
          [0.0247, 0.0311, 0.0283, 0.0405, 0.0316],
          [0.0442, 0.0282, 0.0274, 0.0385, 0.0406],
      